### ISSUE TITLE
oped command does not get blocked

### ISSUE THREAD

**Issue by CloudeLecaw** [DoNotSpamPls/eZProtector#19]
when i hope the title says everyting,

OPed players can use all command listed in the blacklist of OPed commands...
this was working a few versions ago....

**Comment by DoNotSpamPls** [comment]
Opped commands is a dumb feature, since you can just add -whatever.permission to disable access to a command, even for an opped player. Also, 70% of the plugin's users don't even use it. I plan to remove it in the next release. As I've said many times, I don't want to reinvent the wheel with this plugin, just use proper permissions.

**Comment by CloudeLecaw** [comment]
ur right u can handle all by permissionnegation and also OP is an outdated relict of minecraft
but currently the feature is inside, so you should make it work aggain (it was working correct in the old 3.1.6 beta) or u take the statement to say "its an relict and is not needed because u can handle it by permission (and so by your ranks and not by an optitle that is really nonsense when work with a good permission manager)" but then u should take the feature out to clearly define that this thing is no part of the plugin anymore... So finally to say...pls fix it or take it out ;)
