### ISSUE TITLE
Support for 1.11 and lower

### ISSUE THREAD

**Issue by Matocolotoe** [DoNotSpamPls/eZProtector#43]
**Describe the feature you'd like to have implemented**
At least **one** stable release for 1.11 and lower since, yes, a lot of people still use these versions, especially 1.8.8 and 1.9.4

**Is your feature request related to an existing problem? Please describe.**
Not a problem, but looking at the code, shouldn't be **that** hard, at least once ?
If it is, maybe I could help with a pull request if I'm able to do it

**Comment by Matocolotoe** [comment]
Reason = ?

**Comment by DoNotSpamPls** [comment]
Not supporting versions below 1.12.2 is an intentional choice - nobody should be required to support 4-year old versions anymore, and I don't plan to do that for eZProtector. If you want to use it on your server with older versions, feel free to fork the plugin or compile an older version of the source code. However, support is not to be expected.

**Comment by Matocolotoe** [comment]
1. If nobody should be required to support a 4-year version, you should have went yelling at Hypixel when they said they might remove 1.9+ support and stay on 1.8
2. 1.11.X, 1.12.0 and 1.12.1 are not 4-year old versions, I didn't say "pLeAse SuPpoRt 1.8 !!!"
3. You didn't even read the last part of my message where I could say I could help with supporting these versions to help people who are looking for your plugin in these versions (cf. spigot page), but if you take it like that, okay

**Comment by DoNotSpamPls** [comment]
1. Hypixel code everything themselves - if they want to do it, that's on them. 
2. Only two of the versions you mention (1.11.2 and 1.12.0) even show up on bStats, with the others being such a minority that they are grouped under the "Other" category. I don't see any reason anyone should be running those versions when 1.12.2 is objectively better.
3. I don't need help to support those versions, it's a relatively simple fix. As I said, it's an intentional choice (however, I do use an event that doesn't exist in versions lower than 1.9.4). Also, the plugin will be removed from Spigot soon and moved to the Paper forums

**Comment by Matocolotoe** [comment]
At least if you don't want to support those versions why don't you want some people to do it if you told me it's just a single event and a "relatively simple fix" ? And then it'd be the choice of somebody else lol (unless clicking on the "Merge" button is ... hard ?)

**Comment by DoNotSpamPls** [comment]
I will say it one last time - **it's an intentional choice**. Those versions are unsupported by the Spigot/Paper teams themselves, why should I support them? That's a bit like asking for the latest Chrome version to work on Windows XP. Is it possible? Yes. Do they care? Absolutely not.

**Comment by drtshock** [comment]
The project is open source. You're free to fork and maintain your own branch for another version if you want without @DoNotSpamPls's permission.

**Comment by Matocolotoe** [comment]
Okay, I'll just stop there. But remember, if people stay in 1.11, 1.9 or 1.8, there is a valid reason behind, and these people don't have to be considered as stupid nerds because they don't follow the recent versions.

As suggested by somebody on the Spigot page, you should at least provide a link to the latest stable version that works in 1.11 and lower.

@drtshock I suggested the pull request thing because I'm not the only one to suggest 1.11- support, but nevermind

Oh and one last thing, 1.12.2 is **not** actively supported anymore as recent versions are such as 1.14.2 neither by Spigot nor by Paper, unless in case of a big security issue
