### ISSUE TITLE
Disable TAB complete for commands that player have no permissions to it

### ISSUE THREAD

**Issue by arriansamsul** [DoNotSpamPls/eZProtector#49]
**Describe the feature you'd like to have implemented**
Disable TAB completion for commands that players have no permissions to it.
Meaning if a player simply does not have permissions to use that command, TAB completion would be disabled for that command.

**Is your feature request related to an existing problem? Please describe.**
TAB complete is done for individual commands but it can be an extreme amount of work to write down every single commands that you don't want them to see. Especially when the plugin has 100+ commands. Another thing is that I want players from other ranks to see commands while other players can't and also to have support with other worlds (with Multiverse). As a perfectionist, it's kinda irritating knowing that your players' screen is filled with countless commands they will never use. 

**Additional context**
1. Have support with other worlds
2. Disable TAB complete for ranks that don't have the permission.

**Comment by DoNotSpamPls** [comment]
The plugin can't check if players have the permission to tab complete a certain command, simply because it can't know the permission for that command.

From what I understand, you want players to see less commands - issue #32 talks about that. I am currently working on adding a whitelist, so only the commands you define in the config will show up in the list and be completable. If you have anything to add to that, feel free to comment that issue.
